### ISSUE TITLE
Task fails when trying out the actor - ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by hajnyon** [Apifier/act-page-analyzer#18]
I wanted to try this actor directly from market place (https://apify.com/apify/page-analyzer) but run into unhandled error on the first try. Log follows.

```
2021-07-07T18:39:02.477Z ACTOR: Pulling Docker image from repository.
2021-07-07T18:39:12.886Z ACTOR: Creating Docker container.
2021-07-07T18:39:13.316Z ACTOR: Starting Docker container.
2021-07-07T18:39:16.177Z internal/modules/cjs/loader.js:490
2021-07-07T18:39:16.178Z   throw new ERR_PACKAGE_PATH_NOT_EXPORTED(basePath, mappingKey);
2021-07-07T18:39:16.178Z   ^
2021-07-07T18:39:16.179Z 
2021-07-07T18:39:16.179Z Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './underscore-min' is not defined by "exports" in /home/myuser/node_modules/underscore/package.json
2021-07-07T18:39:16.180Z     at applyExports (internal/modules/cjs/loader.js:490:9)
2021-07-07T18:39:16.180Z     at resolveExports (internal/modules/cjs/loader.js:506:23)
2021-07-07T18:39:16.180Z     at Function.Module._findPath (internal/modules/cjs/loader.js:634:31)
2021-07-07T18:39:16.181Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
2021-07-07T18:39:16.181Z     at Function.resolve (internal/modules/cjs/helpers.js:78:19)
2021-07-07T18:39:16.182Z     at Object.<anonymous> (/home/myuser/node_modules/apify/build/puppeteer_utils.js:36:32)
2021-07-07T18:39:16.182Z     at Module._compile (internal/modules/cjs/loader.js:1137:30)
2021-07-07T18:39:16.183Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
2021-07-07T18:39:16.183Z     at Module.load (internal/modules/cjs/loader.js:985:32)
2021-07-07T18:39:16.184Z     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
2021-07-07T18:39:16.184Z     at Module.require (internal/modules/cjs/loader.js:1025:19)
2021-07-07T18:39:16.185Z     at require (internal/modules/cjs/helpers.js:72:18)
2021-07-07T18:39:16.185Z     at Object.<anonymous> (/home/myuser/node_modules/apify/build/crawlers/puppeteer_crawler.js:22:24)
2021-07-07T18:39:16.186Z     at Module._compile (internal/modules/cjs/loader.js:1137:30)
2021-07-07T18:39:16.186Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
2021-07-07T18:39:16.187Z     at Module.load (internal/modules/cjs/loader.js:985:32)
2021-07-07T18:39:16.187Z     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
2021-07-07T18:39:16.188Z     at Module.require (internal/modules/cjs/loader.js:1025:19)
2021-07-07T18:39:16.188Z     at require (internal/modules/cjs/helpers.js:72:18)
2021-07-07T18:39:16.189Z     at Object.<anonymous> (/home/myuser/node_modules/apify/build/index.js:25:49)
2021-07-07T18:39:16.189Z     at Module._compile (internal/modules/cjs/loader.js:1137:30)
2021-07-07T18:39:16.189Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10) {
2021-07-07T18:39:16.190Z   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
2021-07-07T18:39:16.190Z }
```

**Comment by EgorovM** [comment]
Any news?
